#!/bin/bash

FILE="CoppeliaSim_Edu_V4_6_0_rev14_Ubuntu20_04"
URL="https://www.coppeliarobotics.com/files/V4_6_0_rev14/${FILE}.tar.xz"

if [ ! -f "/tmp/${FILE}" ]; then
  echo "Downloading ${FILE} from $URL"
  wget -q --show-progress $URL -O "/tmp/${FILE}.tar.xz"
fi

tar -xf "/tmp/${FILE}.tar.xz" -C /tmp/
mv /tmp/$FILE /opt/coppelia-sim-edu
